### ISSUE TITLE
渠道服分数倍率调整导致进度显示不正确

### ISSUE THREAD

**Issue by chzhong** [infinityedge01/Kyaru#5]
目前国服（渠道服）已经把各阶段的伤害得分倍率进行了调整，参考：[11月24日「团队战」开启预告
](https://www.bilibili.com/read/cv14038057)，导致目前排名查询站点各工会的进度不正确。希望尽快修复。

调整情况：
![会战倍率调整](https://i0.hdslb.com/bfs/article/88109fba127e191e1e7a95905082431f42e372f4.jpg@942w_531h_progressive.webp)

**Comment by infinityedge01** [comment]
已修复
